snapcore/core

COPYING
This project lacked a dedicated license file. The hook is licensed as GPL-3 but license requires us to copy the full text.
Signed-off-by: Zygmunt Krynicki <zygmunt.krynicki@canonical.com>
=> Add GPL-3 license

Makefile, snapcraft.yaml
bump version strings in Makefile and snapcraft.yaml (16.04.1 is wrong, the new versioning can not be implemented until https://launchpad.net/bugs/1611439 is fixed, as an interim use 16-2 as version everywhere)
=> do not show an outdated version for core snap and manifest file

Makefile
This temporarily adds a new snappy-dev/edge2 PPA to allow uploading 2.23 (which already was uploaded to the other ppas because it was almost released but then wasn't).
=> add snappy-dev/edge2 ppa to allow 2.23 in a ppa

Makefile
This was only needed briefly for 2.23 because that version already exited in the existing PPAs (because it was almost released but then we discovered some issues in testing and it got postponed).
=> undo adding of ppa:snappy-dev/edge2 again

.travis.yml, Makefile, hooks/configure, tests/test_hook_pi_config.py
This branch allows configuring the pi{2,3} config.txt file via `snap set core pi-config.*`. It supports the options discussed in LP #1587137 
E.g. `snap set core pi2-config.disable-overscan=1` will set `disable_overscan=1` in `/boot/uboot/config.txt`.
Once that has landed I can also write a spread test in snapd to test this end-to-end instead of the mocking stuff that is currently done in the tests.
=> configure: add support for pi2 config.txt updates

.travis.yml
this cuts off 3-4min from each test run by using the daily xenial ubuntu-base tarballs directly
=> use ubuntu-base tarballs instead of debootstrap to speed up tests

snapcraft.yaml
This patch adds gawk to build-packages. We are currently seeing build
failures on the launchpad "core" snap recipe. They all complain about
--sanbox being an unknown option. This is a quick shoot in the dark.
Signed-off-by: Zygmunt Krynicki <zygmunt.krynicki@canonical.com>
=> Build depend on gawk

snapcraft.yaml
This can only land if https://github.com/snapcore/snapd/pull/3166 lands.
=> the core snap only needs core-support  (not network-bind)

.travis.yml, live-build/hooks/300-create-classic-diff.binary
- make sure we have a valid archive keyring in place to prevent gpg issues (part of LP: #1670475)
- force-run apt-get update when we create the classic chroot
- tests: drop wrong shellcheck version, it runs inside the chroot during build with the right version instead.
=> install keyring (LP: #1670475), update pkglists

live-build/hooks/09-disable-cloud-init-net-breaking.chroot, live-build/hooks/40-cloud-init-run-after-networkd-wait-online.chroot
- cloud-init handles working with UC16's built-in netplan configuration without disabling cloud-init's network configuration
- Ensure that cloud-init service works with networkd;  cloud-init in Xenial (which doesn't use
networkd by default) can't change packaging so adjust core configuration.
=> Update core snap cloud-init configuration

Makefile, README.md, snapcraft.yaml
This adds version information to the core snap. 
Also updates the readme as the snapcraft will fail when running on a non 16.04 system.
=> add version-script

live-build/hooks/08-etc-writable.chroot
https://bugs.launchpad.net/snappy/+bug/1650688 might potentially be fixed by this (our systemd already ships http://paste.ubuntu.com/24559979/)
=> make links to /etc/writable absolute

snapcraft.yaml
The version number has a `16-` prefix so the amount of version number information in the suffix is only 29 chars, not 32 :)
=> fix version number length

hooks/configure
following the discussion at https://forum.snapcraft.io/t/change-in-logging-behaviour-on-ubuntu-core/591
and https://bugs.launchpad.net/snappy/+bug/1587453 allow to use the service.rsyslog.disable=true|false setting to select if syslog should be running.
=> allow rsyslog disabling

snapcraft.yaml
Tiny branch to make the version number of the core snap equal to what mkversion.sh would do.
This is needed because the PPA version number will automatically add ` ~ubuntu16.04` (and similar) for each distro.
=> cut the trailing ~ubuntu16.04 from the version that the PPA auto-generates

live-build/hooks/300-create-classic-diff.binary, live-build/hooks/600-no-debian.binary
- remove all generated dpkg logfiles created during build
- remove lsb-release binary more cleanly (and add it to the classic diff instead)
- drop unneeded cron jobs (dpkg and passwd backups)
=> remove generated logs, cleaner lsb-release removal

live-build/hooks/500-create-xdg-wrapper.binary
do not put xdg-open into /usr/local. we kept it there initially with the possibility of a personal-core snap in mind where the real xdg-open would be included but this is unlikely to happen. instead of having to mangle the PATH variable in snap wrappers the binary can now be found right away in $PATH without extra adjustment.
=> move xdg-open to proper paths

live-build/hooks/26-fixup-core.chroot
The deb packages only installs /etc/.../multi-user.target.wants but for core we need it in /lib
=> fix snapd.core-fixup.service symlink on core devices

Makefile
due to a recent change in launchpad-buildd, builds do not run as root anymore but the build environment provides a passwordless sudo setup, so we need to prefix all our root-requiring
commands with sudo to make the snap build again.
=> use sudo to work around LP: #1702656

live-build/hooks/26-fixup-core.chroot
The snapd deb will install the snap-repair.timer symlink into
/etc/systemd/system/timers.target.wants/snap-repair.timer
However on a refresh on a core device this path will not
show up because of the way that our writable path system
works. It will not merge existing directories. Fortunately
we can simply install the unit in /lib.
=> Ensure the snap-repair.timer is available on refresh as well

live-build/hooks/20-extra-files.chroot
This PR is based on discussions from the following forum thread:
https://forum.snapcraft.io/t/desktop-allow-access-to-host-system-fonts/1796
We want to mount the host system's fonts, fontconfig configuration files, and global fontconfig cache at the same file system locations within the sandbox.  Zygmunt suggested that creating the empty directories to use as mount points in the core snap would be a better option than waiting for his layouts work to complete (and presumably for follow on work allowing interfaces to affect the layout of a snap).
=> Create mount points for use in exposing host system fontconfig

live-build/hooks/500-create-xdg-wrapper.binary
This is the companion for https://github.com/snapcore/snapd/pull/3260
on the snapd side.
Note that this can only be merged after https://github.com/snapcore/snapd/pull/3260 is merged.
=> Use io.snapcraft.Launcher instead of com.canonical.SafeLauncher

snapcraft.yaml
This fixes the problem that a version like "2.28\~rc1" shows up
as 2.28 in `snap info core'. The PPA version strings like:
2.27.5+git358.02243d2~ubuntu17.04.1 will still be displayed
correctly as 2.27.5+git358.02243d2.
=> Remove ~ubuntu* instead of cutting after the first "~"

live-build/hooks/500-create-xdg-wrapper.binary
There was a copy/paste error when creating the previous xdg-wrapper helper. This PR fixes this.
=> fix typo in 500-create-xdg-wrapper.binary

live-build/hooks/500-create-xdg-wrapper.binary
This will fix the snapd test failure we are seeing in
https://github.com/snapcore/snapd/pull/3904
=> fix object path used by usr/bin/xdg-open in core

live-build/hooks/27-systemd-defaults.chroot
The default behaviour of the kernel is to take down the secondary
addresses when a primary address goes away. However this is not
what we want with networkd (and the systemd upstream changes this
in its sysctl.d/50-default.conf in the upstream git tree). The
way networkd works is to add a new DHCP IP as a secondary address
and when the previous address goes away the secondary address
needs to be promoted, not removed. This patch fixes this behaviour.
=> Fix handling of secondary addresses

hooks/configure
In addition to disabling services when
`snap set service.{ssh,syslog}.disable=true` is called we need to
mask them. The reason is that the /etc/systemd/system directory
is marked "synced" and the core snap has a "syslog.service" symlink.
So on each boot if there is no "syslog.service" (or ssh) link there
writable-path will happily copy it. This is not what we want. By
using "mask" in addition to disable systemd will create a symlink
with the name of the service to /dev/null. This prevents
writable-path from interfering.
=> Also "mask" services when disabling them

live-build/hooks/25-create-generic-initrd.chroot
There was  a discussion about the core snap files recently. One of the observations was that we currently ship two initrd.img images. This is not a problem as such as squashfs compresses the two identical files away. However it is a problem when a delta is generated via the `bsdiff` mechanism. This method will look into the squashfs data itself and because initrd is compressed it apparently has trouble generating a optional delta.
=> 25-create-generic-initrd.chroot: use symlink instead of copy

live-build/hooks/500-create-xdg.binary
The xdg-settings set will pop up a dialog that needs to be confirmed
by the user. This confirmation may take some time so the default
timeout of ~25sec is too low. We will also make the dialag that
`snap userd` pops up timeout after 5 min.
=> xdg-settings: make the reply timeout for xdg-settings set 5min

live-build/hooks/500-create-xdg.binary
To ensure xdg-settings  dbus call error fail correctly and to avoid that the `| cut` clobbers the error.
The fixes the test failure in https://github.com/snapcore/snapd/pull/4073
=> 500-create-xdg.binary: use "set -o pipefail" 

live-build/hooks/10-remove-documentation.binary, live-build/hooks/12-add-foreign-libc6.chroot
Shellcheck in artful complains about the ordering for `find`, i.e. the first arg must the the path. This PR fixes this.
=> hooks: fix shellcheck complains

live-build/hooks/10-remove-documentation.binary, live-build/hooks/12-add-foreign-libc6.chroot
The order of find is critical for it to work correctly. Each item
after the starting point is evaluated and the resulting return is
used to consider if the term should continue or not. This means
that: "find ./foo -print0 -type f" will *always* call -print0
(and return an implicit "true") and then move on to the "-type f"
test which will return false and the processing will stop for
the given file. So to make things work correctly we need to
write it in the right order as find just evaluates expressions.
=> live-build: fix order of -print0 in find

live-build/hooks/10-remove-documentation.binary
The changelogs in the /usr/share/doc directories are useful when
generating the changes between two core releases. They are also
pretty tiny. We used to have them but with the bugfix for "find"
(in 009c9ff) the find got pretty aggressive and removed them all.
The root cause for this is that some/many of the livebuild hooks
do not `set -e` - I will do a separate PR for this.
=> 10-remove-documentation: preserve changelogs

live-build/hooks/12-add-foreign-libc6.chroot
This patch will allow armhf binaries to run on an arm64 (aarch64) operating system by installing the libc6;armhf libraries to the core snap.
Confirmed it works and builds successfully on an arm64 os (Armbian)
it is analogous to patch for running i386 binaries on amd64 operating systems and duplicates that logic so there could be some refactoring to de-dupe, but not necessary for it to work
=> Support for armhf binaries on arm64 (aarch64) operating system

live-build/hooks/29-fix-ld-so-symlink.chroot
This should help with bug:
https://bugs.launchpad.net/snapd/+bug/1684063
Right now classic snaps will fail on distros (like zesty) that
have a different version of the dynamic linker than xenial.
=> live-build: make /lib64/ld-linux-x86-64.so.2 a relative link

live-build/hooks/28-command-not-found.chroot
Once https://github.com/snapcore/snapd/pull/4450 lands we can just use a symlink for `command-not-found`.
=> hooks: use symlink to run `snap advise-command`

live-build/hooks/01-setup_user.chroot, live-build/hooks/03-boot_with_systemd.chroot, live-build/hooks/05-create_minimal_fstab.chroot, live-build/hooks/07-configure-system-image-client.chroot, live-build/hooks/08-etc-writable.chroot, live-build/hooks/10-remove-documentation.binary, live-build/hooks/11-remove-extra-packages.chroot, live-build/hooks/12-add-foreign-libc6.chroot, live-build/hooks/13-set-locale.chroot, live-build/hooks/14-set-motd.chroot, live-build/hooks/15-remove-grub-common.chroot, live-build/hooks/16-ensure-bootloaders.chroot, live-build/hooks/19-remove-cloud-init-locale-test.chroot, live-build/hooks/20-extra-files.chroot, live-build/hooks/21-snappy-security-policy-stamp.chroot, live-build/hooks/22-setup-path.chroot, live-build/hooks/25-create-generic-initrd.chroot, live-build/hooks/26-fixup-core.chroot, live-build/hooks/27-systemd-defaults.chroot, live-build/hooks/30-fix-timedatectl.chroot, live-build/hooks/300-create-classic-diff.binary, live-build/hooks/40-cloud-init-run-after-networkd-wait-online.chroot, live-build/hooks/400-create-apt-get-warning.binary, live-build/hooks/500-create-xdg.binary, live-build/hooks/600-no-debian.binary, live-build/hooks/700-classic-dir.binary, live-build/hooks/99zz-check-uid-gid.chroot
It turns out that some scripts did not use `set -e` which lead to some scripts being buggy for a long time (e.g. 10-remove-documentation.binary). This PR ensures we add it everywhere.
Please do not merge just yet, we need to build one more core today and this may break the build (or not, we don't know).
=> ensure that all live-build/hooks run with `set -e`

live-build/hooks/14-set-motd.chroot
It has been observed that the motd displayed when the ssh connection to
Ubuntu Core has been established contains inaccurate and desktop-centric
information, such as:
Welcome to Ubuntu Core 16 (GNU/Linux 4.1.29-g8050069-dirty armv7l)
* Documentation:  https://help.ubuntu.com
* Management:     https://landscape.canonical.com
* Support:        https://ubuntu.com/advantage
Welcome to Snappy Ubuntu Core, a transactionally updated Ubuntu.
* See https://ubuntu.com/snappy
It's a brave new world here in Snappy Ubuntu Core! This machine
does not use apt-get or deb packages. Please see 'snap --help'
for app installation and transactional updates.
This commit fixes it by correcting the /etc/motd content to match the
current naming scheme (Snappy Core -> Core) and provide correct
documentation links. …
=> hooks: update the set-motd hook to provide better motd

live-build/hooks/15-remove-grub-common.chroot
It contains "/." which cannot be removed.
=> 15-remove-grub-common.chroot: skip the first line in grub-common.list

live-build/hooks/26-fixup-core.chroot
The name of this service changed but the fixup script was not updated.
=> 26-fixup-core.chroot: fix snapd.snap-repair.timer enable symlink

.travis.yml, live-build/hooks/500-create-xdg.binary, snapcraft.yaml, xdg-open/Makefile, xdg-open/mimeapps.list, xdg-open/xdg-open.c, xdg-open/xdg-open.desktop
This PR is the core snap complement to https://github.com/snapcore/snapd/pull/4766
It replaces the xdg-open proxy to call the new `OpenFile` D-Bus method if a local file is passed as an argument.
Since `OpenFile` expects a file descriptor as proof of access, the `dbus-send` was no longer usable.  So I've replaced it with a C implementation using glib/gio's D-Bus implementation.
=> xdg-open: add implementation capable of opening local files

live-build/hooks/26-fixup-core.chroot
This creates a compatibility copy /usr/lib/snapd/snap-device-helper
to /lib/udev/snappy-app-dev so that an old snap-confine will work
correctly with a new core snap. The snappy-app-dev binary got
renamed and while we provided a symlink this is not sufficient
because the apparmor profile for snap-confine does only allow
running /lib/udev/snappy-app-dev.
=> hooks: create compat copy of /lib/udev/snappy-app-dev

live-build/hooks/29-fix-ld-so-symlink.chroot
This will fix the ppc64el autopkgtest that uses the go1.10 classic snap.
=> hooks: make /lib64/ld64.so.2 relative to unbreak classic snaps on ppc64el

live-build/hooks/30-fix-timedatectl.chroot
This should fix the errors we see when running timedatectl from a snap when running on classic, e.g:  https://github.com/snapcore/snapd/pull/5405
=> hooks: fix 30-fix-timedatectl.chroot to DTRT when running on non-core devices

live-build/hooks/30-fix-timedatectl.chroot
This fixes a rather silly copy/paste issue the symlink handling was done twice.
=> hooks: fix silly copy/paste error from PR#89

snapcraft.yaml
This patch removes core-support plug from the core snap. Eventually we will be able to remove the interface entirely but for now this is the next best thing.
=> Remove core-support plug

live-build/hooks/02-check-package-env.chroot
When triggering a build in LP it is possible to trigger it without
the required lp:snappy-dev/image PPA. This will produce a working
build but the resulting core snap will not work properly and fail
in confusing ways.
This PRs ensures it fails early and in obvious ways.
=> hooks: add a check to ensure that the image is build with ppa:snappy-dev/image

.travis.yml, live-build/hooks/91-unwind-alternatives.chroot
The core snap currently ships with a bunch of files pointing to
/etc/alternatives. E.g.
/usr/bin/awk -> /etc/alternatives/awk -> /usr/bin/gawk
This is problematic because /etc is mounted from the host so
a user how configured a different awk which is not part of
core will have a dangling symlink (because /usr comes from
the core snap of course).
There is a small risk with this PR as it changes the existing
behaviour. However I would argue its worth it because the
current "awk" that you get in the core snap depends on the
host you run your snap in. Which is not the predictable
behaviour we want.
=> hooks: unwind /etc/alternatives

live-build/hooks/91-unwind-alternatives.chroot
The previous approach of unwinding alternatives had the problem
that e.g. /usr/bin/pager -> /etc/alternatives/pager -> /bin/more
would end up with a "/bin/pager".
This PR fixes this bug. It also splits the alternatives finding
into its own hook script.
=> hooks: improve /etc/alternatives unwinding

live-build/hooks/92-cleanup-init-functions.chroot
Remove including the /etc/lsb-base-logging.sh. The issue here is that
the host might have this script. However for snaps that run under
confinement including this will fail with a permission error which
breaks existing snaps (like mysql).
This fixes LP: #1779416
=> hooks: Remove including the /etc/lsb-base-logging.sh

live-build/hooks/91-unwind-alternatives.chroot
The /etc/alternatives unwinding is currently creating absolute
paths. This can cause problems for classic snaps. The issue is
that on a classic snap /snap/core/current/usr/bin/awk will point
to /usr/bin/gawk - however this awk version may not be installed
on the host machine. Ironically this worked before because the
/snap/core/current/usr/bin/awk points to /etc/alternatives of
the host which may point to e.g. mawk (but potentially everyone
using the snap would see a different awk version).
This PR fixes this by using relative symlinks when unwinding the
alternatives. So it will /usr/bin/awk -> ./gawk
This also needs to be ported to core18 unwinding.
=> hooks: use relative path when unwinding /etc/alternatives

snapcraft.yaml
Without this PPA things can go very wrong so we need to ensure we
never build a core with that ppa missing.
=> snapcraft.yaml: add check for ppa:snappy-dev/image

live-build/hooks/20-extra-files.chroot
The 2.37 release has a regression for people using homedirs in
/var/lib/*. The most prominent example is jenkins. To quickly
unblock that we need this dir and
https://github.com/snapcore/snapd/pull/6446
and the same for core18.
=> hooks: add /var/lib/jenkins for compat

live-build/hooks/20-extra-files.chroot
Bind mounting over the /var/lib/jenkins here from the host was covering cases that were not supported even before.
This reverts commit 35082278e27b1939db7294176142dc468f045e14, reversing
changes made to 0ff7b71a345b53463f6281855e23d63f0f130f16.
=> Revert "Merge pull request #100 from mvo5/add-jenkins-dirs"

live-build/hooks/400-create-apt-get-warning.binary
Since apt cannot be used on core, it should be an error and the exit return code
should specify as such.
=> hooks: apt warning should return an error

hooks/configure
The configure hook is no longer used from the core snap. It is
done via the snapd code itself (go based). Hence we can remote
this old shell code.
=> hooks: empty the configure hook

extra-files/etc/system-image/writable-paths
This is a useful property on its own but its also important to get
https://github.com/snapcore/snapd/pull/7605/files fixed.
=> extra-file: make /etc/systemd/journald.conf.d writable

extra-files/etc/system-image/writable-paths
When the `snapd` snap is installed on an Ubuntu Core 16 system, it tries to write dbus configuration to `/etc/dbus-1/session.d`, which is not currently writable.  This PR adds that directory as a writable path.
=> writable-paths: make /etc/dbus-1/session.d writable

live-build/hooks/93-rm-cloud-init-config.chroot
This configuration file has the following contents:
```
datasource_list: [ NoCloud, ConfigDrive, OpenNebula, DigitalOcean, Azure, AltCloud, OVF, MAAS, GCE, OpenStack, CloudSigma, SmartOS, Bigstep, Scaleway, AliYun, Ec2, CloudStack, Hetzner, IBMCloud, Oracle, Exoscale, RbxCloud, None ]
```
On Ubuntu Core, one cannot run dpkg-reconfigure for one, so the file can never
be modified in practice, and additionally we do not want to allow all possible
datasources under the sun without understanding their use cases in Ubuntu Core.
Note that already on Ubuntu Core, snapd as of 2.45.2 will write a configuration
file zzzz_snapd.cfg taking priority over this file to restrict the set of
datasources to a safe one, so we do not strictly need to delete this file, but
it will be simpler if we don't have …
=> live-build/hooks: add chroot hook to rm cloud-init config file we don't want

extra-files/etc/system-image/writable-paths, live-build/hooks/08-etc-writable.chroot
This is needed for enabling linger in systemd.
Essentially a backport of this core18 PR: https://github.com/snapcore/core18/pull/6
CC @zyga
=> extra-files/writable-paths: make all /var/lib/systemd writable

extra-files/etc/system-image/writable-paths
This file is used to manage wireless regulatory domains, so it should be writable to allow setting REGDOMAIN in this file.
It's still unclear which snaps / interfaces should actually manage this file, but that can be handled easily with a system-files interface plug in the meantime, but system-files can't make this file writable so we need writable-paths(5) for that.
=> extrafiles/writable-paths: make /etc/default/crda writable

.travis.yml, live-build/hooks/600-no-debian.binary
On ESM enabled builds of core, delete the ESM repository tokens that
could be left behind by new-enough livecd-rootfs from snappy-dev/image
ppa.
=> live-build: remove ESM tokens, if any are present

Makefile
We will need to copy the yaml file in order to be able to gather it from the Buildd output folder.
=> Copy dpkg.yaml for LP Buildd

snapcraft.yaml
The /usr/lib/snapd/info now contains more than just the version
number. This leads to a version number in the snap that contains
a \n which is of course illegal.
This commit fixes this by adding a proper grep around the version
number.
=> snapcraft.yaml: account for new "info" file

Makefile, live-build/hooks/02-check-package-env.chroot, live-build/hooks/600-no-debian.binary, snapcraft.yaml
We now have a new HTTPS-capable domain for public PPAs, namely
ppa.launchpadcontent.net.  Adjust various bits of the build system to
accept that.
=> Handle PPAs being served from ppa.launchpadcontent.net

live-build/hooks/20-extra-files.chroot
Snaps using the cups interface with the cups snap as of snapd 2.55 will create
a bind mount of /run/cups -> /var/cups, which since /var/cups does not exist
will trigger the writable mimic code to create a writable mimic on /var. This
results in a fair amount of extra bind mounts for every directory in /var, so
creating this directory empty in the base snap ensures that no writable mimic
need be created.
Note that this will result in review-tools complaining when this is merged and a
new core is uploaded since a new directory is being added to the base snap,
but this is okay.
Also, we can close this PR if we decide that it's not worth updating core anymore
for this sort of feature since `base: core` snaps should be on the way out...
=> hooks: mkdir /var/cups to avoid writable mimic creation for snaps using cups

live-build/hooks/600-no-debian.binary
With the introduction of https://github.com/snapcore/snapd/pull/11600
now the `fuse` package is installed on `core`. However we do not
want this. This commit forcefully removes it if it gets installed.
There is also a followup https://github.com/snapcore/snapd/pull/11648
that will downgrade fuse to a recommends.
=> hooks: remove "fuse" from the core snap
